development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: shakmog_dev
  pool:     5
  username: shak
  password: 
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: shakmog_production
  pool:     5
  username: shak
  password: 
  template: template0